[package]
name = "challenge-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
maelstrom-node = "0.1.6"
serde_json = "1.0.99"
uuid = { version = "1.4.0", features = ["v4"] }
